USE [master]
GO

/****** Object:  Database [CloudBank]    Script Date: 9/19/2017 10:06:35 AM ******/
CREATE DATABASE [CloudBank]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CloudBank', FILENAME = N'W:\Databases\newdate\MSSQL12.MSSQLSERVER\MSSQL\DATA\CloudBank.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CloudBank_log', FILENAME = N'W:\Databases\newdate\MSSQL12.MSSQLSERVER\MSSQL\DATA\CloudBank_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CloudBank] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CloudBank].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CloudBank] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CloudBank] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CloudBank] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CloudBank] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CloudBank] SET ARITHABORT OFF 
GO

ALTER DATABASE [CloudBank] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CloudBank] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CloudBank] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CloudBank] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CloudBank] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CloudBank] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CloudBank] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CloudBank] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CloudBank] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CloudBank] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CloudBank] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CloudBank] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CloudBank] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CloudBank] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CloudBank] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CloudBank] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CloudBank] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CloudBank] SET RECOVERY FULL 
GO

ALTER DATABASE [CloudBank] SET  MULTI_USER 
GO

ALTER DATABASE [CloudBank] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CloudBank] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CloudBank] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CloudBank] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CloudBank] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CloudBank] SET  READ_WRITE 
GO


